#!/bin/zsh

#
# /etc/zshenv
#


# XDG home directories
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# zsh
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

# ohmyzsh
export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/oh-my-zsh"

# increase file limit
ulimit -n 1000000

