#!/bin/sh

#
# /etc/profile
#

# set mask
umask 022

# get user id
uid="$(id -u)"

# --------------------------------------------------
# path
# --------------------------------------------------

# append a given path to PATH
append_path () {
  case ":${PATH}:" in
    *":$1:"*)
      ;;
    *)
      PATH="${PATH:+"${PATH}:"}$1"
  esac
}

# append default paths
append_path '/usr/local/sbin'
append_path '/usr/local/bin'
append_path '/usr/bin'

# export PATH to environment
export PATH

# --------------------------------------------------
# environment variables
# --------------------------------------------------

# XDG directories
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# XDG runtime directory
if pidof systemd >/dev/null 2>&1; then
  export XDG_RUNTIME_DIR="/run/user/${uid}"
else
  mkdir --parents "/tmp/user/${uid}"
  export XDG_RUNTIME_DIR="/tmp/user/${uid}"
fi

# --------------------------------------------------
# source config files
# --------------------------------------------------

# source profiles from /etc/profile.d
if [ -d /etc/profile.d/ ]; then
  for profile in /etc/profile.d/*.sh; do
    [ -r "${profile}" ] && . "${profile}"
  done
  unset profile
fi

# source the global bashrc if applicable
if [ -n "${BASH}" ] && [ -n "${PS1}" ] && [ -z "${POSIXLY_CORRECT}" ] && \
   [ "${0#-}" != "sh" ] && [ -r /etc/bash.bashrc ]; then
  . /etc/bash.bashrc
elif [ "${uid}" -eq 0 ]; then
  PS1='# '
else
  PS1='$ '
fi

# --------------------------------------------------
# cleanup environment
# --------------------------------------------------

# unset functions
unset -f append_path

# unset variables
unset TERMCAP MANPATH uid

